debug: true
logLevel: DEBUG

providers:
  docker:
    exposedByDefault: false

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ":443"

tls:
  entryPoints:
    - websecure
  certificates:
    - certFile: /etc/certs/signed.crt
      keyFile: /etc/certs/domain.key
