version: "3"

services:
  reverse-proxy:
    image: traefik:v2.4
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik.yml:/etc/traefik/traefik.yml:ro
      # Generated certificates are stored in `/letsencrypt/acme.json`.
      - letsencrypt:/letsencrypt

  whoami:
    image: traefik/whoami
    labels:
      # `traefik.enable=true` is required if `providers.docker.exposedByDefault = false`
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.whoami.tls=true"
      - "traefik.http.routers.whoami.tls.certresolver=myresolver"
      - "traefik.http.routers.whoami.entrypoints=web,websecure"
      - "traefik.http.services.whoami.loadbalancer.server.port=80"

volumes:
  # Volume for certificates
  letsencrypt:
